[2022-04-30T10:54:24.170338+00:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","template":"default/homepage.html.twig","_locale":"en","_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController::templateAction"},"request_uri":"http://localhost/","method":"GET"} []
[2022-04-30T10:54:24.172980+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2022-04-30T10:54:24.172986+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T10:54:24.172992+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T10:54:24.172994+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T10:54:24.173000+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T10:54:24.214703+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "blog_rss" as such route does not exist.")." at /home/bugrahan/case_study/templates/base.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"blog_rss\" as such route does not exist.\"). at /home/bugrahan/case_study/templates/base.html.twig:12)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"blog_rss\" as such route does not exist. at /home/bugrahan/case_study/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []
[2022-04-30T11:58:53.795845+00:00] request.INFO: Matched route "homepage". {"route":"homepage","route_parameters":{"_route":"homepage","template":"default/homepage.html.twig","_locale":"en","_controller":"Symfony\\Bundle\\FrameworkBundle\\Controller\\TemplateController::templateAction"},"request_uri":"http://localhost/","method":"GET"} []
[2022-04-30T11:58:53.798840+00:00] security.DEBUG: Checking for authenticator support. {"firewall_name":"main","authenticators":2} []
[2022-04-30T11:58:53.798847+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T11:58:53.798853+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\FormLoginAuthenticator"} []
[2022-04-30T11:58:53.798855+00:00] security.DEBUG: Checking support on authenticator. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T11:58:53.798861+00:00] security.DEBUG: Authenticator does not support the request. {"firewall_name":"main","authenticator":"Symfony\\Component\\Security\\Http\\Authenticator\\HttpBasicAuthenticator"} []
[2022-04-30T11:58:53.827165+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "blog_rss" as such route does not exist.")." at /home/bugrahan/case_study/templates/base.html.twig line 12 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"blog_rss\" as such route does not exist.\"). at /home/bugrahan/case_study/templates/base.html.twig:12)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\RouteNotFoundException(code: 0): Unable to generate a URL for the named route \"blog_rss\" as such route does not exist. at /home/bugrahan/case_study/vendor/symfony/routing/Generator/CompiledUrlGenerator.php:50)"} []
